name: Comprobaciones de Compilacion jijijuaz

on:
  push:
    branches: [ "main" ]

jobs:
  pruebas-python:
    name: Pruebas de codigo y Cobertura
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar librerias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pytest y generar XML
        run: |
          pytest --cov=. --cov-report=xml:clover.xml

      - name: Subir reporte XML como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura
          path: clover.xml

  comprobacion-build:
    name: Validar con docker/build
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4
        
      - name: Configurar motor Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Ejecutar comprobacion (docker/build)
        uses: docker/build-push-action@v6
        with:
          context: .
          call: check

  comprobacion-bake:
    name: Validar con docker/bake
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4
        
      - name: Configurar motor Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Ejecutar comprobacion (docker/bake)
        uses: docker/bake-action@v5
        with:
          targets: validate-build

  comprobacion-bake-fork:
    name: Validar con nuestro fork
    needs: [comprobacion-build, comprobacion-bake, pruebas-python]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar motor Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Iniciar sesion en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Ejecutar comprobacion (johnnytester20/bake)
        uses: johnnytester20-source/bake-action@master
        with:
          push: true
          files: |
            ./docker-bake.hcl
